---

# Application settings.
virtualenv_path: "/var/virtualenv/{{ application_name }}"
project_path: "/var/www/{{ project_name }}"
application_log_dir: "/tmp/logs"
application_log_file: "{{ application_log_dir }}/gunicorn_supervisor.log"
requirements_file: "{{ project_path }}/requirements.txt"


# Gunicorn settings
app_user: "{{ application_name }}"
app_group: "{{ application_name }}"

# Supervisor settings
program_group: "{{ application_name }}:"

# Nginx settings
nginx_http_port: 80
nginx_https_port: 443
nginx_access_log_file: "{{ application_log_dir }}/nginx_access.log"
nginx_error_log_file: "{{ application_log_dir }}/nginx_error.log"
nginx_static_dir: "{{ project_path }}/static/"


# Flask App Environment variables
app_environment:
  STATIC_ROOT: "{{ nginx_static_dir }}"
  DATABASE_URL: "{{ db_url }}"
  DATABASE_USER: "{{ db_user }}"
  DATABASE_PASSWORD: "{{ db_password }}"
